name: Deploy GuessPokemon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t guess_pokemon:latest .

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_github
        chmod 600 ~/.ssh/id_rsa_github
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        HOSTNAME: ${{ secrets.HOSTNAME }}
        PHX_HOST: ${{ secrets.PHX_HOST }}
        LIVE_VIEW_SIGNING_SALT: ${{ secrets.LIVE_VIEW_SIGNING_SALT }}
        SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      run: |
        docker save guess_pokemon:latest | ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_github root@$SSH_HOST "docker load"
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_github root@$SSH_HOST << 'EOF'
        docker stop guess_pokemon || true
        docker rm guess_pokemon || true
        docker run -d --name guess_pokemon -p 80:4000 guess_pokemon:latest
        EOF